### ISSUE TITLE
Mod cannot load on newest forge version

### ISSUE THREAD

**Issue by PhamKun** [zKryle/JustEnoughGolems#12]
**Describe the bug**
Forge had a massive breaking change in 41.0.64, so the mod stop working. Minecraft will give you screen that say the mod failed to load correctly

**To Reproduce**
- Install the mod with the newest forge version
- Launch Minecraft
- Minecraft will give you screen that say the mod failed to load correctly

**Expected behavior**
- Minecraft launcher regularly 

**Screenshots**
[image](https://user-images.githubusercontent.com/23272742/182159877-53111924-6f83-48ae-91b4-f0b30b52e0cc.png)

**Version:**
- 1.19 

**Additional context**

**Comment by zKryle** [comment]
Fixed in latest release.
