### ISSUE TITLE
Charging Table Crashes Server Upon Placing

### ISSUE THREAD

**Issue by StoneMasons4106** [zKryle/JustEnoughGolems#8]
**Describe the bug**
Upon placing the Charging Table, the server crashes almost immediately.

**To Reproduce**
Place the table. That's it.

**Expected behavior**
For the server not to crash.

**Screenshots**
No screenshots available.

**Version:**
- 1.18.1, Forge 39.0.64
- Additional mods running specified in the crash report.

**Additional context**
[crash-2022-02-01_16.49.58-server.txt](https://github.com/zKryle/JustEnoughGolems/files/7982368/crash-2022-02-01_16.49.58-server.txt)

**Comment by zKryle** [comment]
> **Describe the bug**
> 
> Upon placing the Charging Table, the server crashes almost immediately.
> 
> 
> 
> **To Reproduce**
> 
> Place the table. That's it.
> 
> 
> 
> **Expected behavior**
> 
> For the server not to crash.
> 
> 
> 
> **Screenshots**
> 
> No screenshots available.
> 
> 
> 
> **Version:**
> 
> - 1.18.1, Forge 39.0.64
> 
> - Additional mods running specified in the crash report.
> 
> 
> 
> **Additional context**
> 
> [crash-2022-02-01_16.49.58-server.txt](https://github.com/zKryle/JustEnoughGolems/files/7982368/crash-2022-02-01_16.49.58-server.txt)
> 
> 
> 
> 

I'll look into it tomorrow! Thanks for the report!
